spring:
  application:
    name:
      architecture


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop


logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
